name: Build and Test

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: self-tracker-flow/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('self-tracker-flow/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: self-tracker-flow
        run: npm ci

      - name: Set up environment variables
        run: |
          echo "NG_APP_FIREBASE_API_KEY=${{ secrets.NG_APP_FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "NG_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.NG_APP_FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "NG_APP_DATABASE_URL=${{ secrets.NG_APP_DATABASE_URL }}" >> $GITHUB_ENV
          echo "NG_APP_FIREBASE_PROJECT_ID=${{ secrets.NG_APP_FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "NG_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.NG_APP_FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "NG_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NG_APP_FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "NG_APP_FIREBASE_APP_ID=${{ secrets.NG_APP_FIREBASE_APP_ID }}" >> $GITHUB_ENV

      - name: Lint code
        working-directory: self-tracker-flow
        run: npm run ci:lint

      - name: Run tests
        working-directory: self-tracker-flow
        run: npm run ci:test

      - name: Build
        working-directory: self-tracker-flow
        run: npm run ci:build
        
      - name: List build output
        working-directory: self-tracker-flow
        run: |
          echo "Contents of dist directory:"
          ls -R dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/self-tracker-flow/browser
