name: Deploy to Firebase

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: List build output before deploy
        working-directory: self-tracker-flow
        run: |
          echo "Contents of dist directory:"
          ls -R dist/

      - name: Deploy to Firebase Hosting
        working-directory: self-tracker-flow
        run: |
          firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
