name: CI

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: self-tracker-flow/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('self-tracker-flow/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: self-tracker-flow
        run: npm ci

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up environment variables
        run: |
          echo "NG_APP_FIREBASE_API_KEY=${{ secrets.NG_APP_FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "NG_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.NG_APP_FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "NG_APP_DATABASE_URL=${{ secrets.NG_APP_DATABASE_URL }}" >> $GITHUB_ENV
          echo "NG_APP_FIREBASE_PROJECT_ID=${{ secrets.NG_APP_FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "NG_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.NG_APP_FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "NG_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NG_APP_FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "NG_APP_FIREBASE_APP_ID=${{ secrets.NG_APP_FIREBASE_APP_ID }}" >> $GITHUB_ENV

      - name: Lint code
        working-directory: self-tracker-flow
        run: npm run ci:lint

      - name: Run tests
        working-directory: self-tracker-flow
        run: npm run ci:test

      - name: Build
        working-directory: self-tracker-flow
        run: npm run ci:build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Change directory to Firebase config
        run: cd self-tracker-flow

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
